CREATE EXTERNAL TABLE IF NOT EXISTS base.states_daily(
  date int,
  state string,
  positive int,
  probablecases int,
  negative int,
  pending int,
  totaltestresultssource string,
  totaltestresults int,
  hospitalizedcurrently int,
  hospitalizedcumulative int,
  inicucurrently int,
  inicucumulative int,
  onventilatorcurrently int,
  onventilatorcumulative int,
  recovered int,
  lastupdateet string,
  datemodified timestamp,
  checktimeet string,
  death int,
  hospitalized int,
  hospitalizeddischarged int,
  datechecked timestamp,
  totaltestsviral int,
  positivetestsviral int,
  negativetestsviral int,
  positivecasesviral int,
  deathconfirmed int,
  deathprobable int,
  totaltestencountersviral int,
  totaltestspeopleviral int,
  totaltestsantibody int,
  positivetestsantibody int,
  negativetestsantibody int,
  totaltestspeopleantibody int,
  positivetestspeopleantibody int,
  negativetestspeopleantibody int,
  totaltestspeopleantigen int,
  positivetestspeopleantigen int,
  totaltestsantigen int,
  positivetestsantigen int,
  fips int,
  positiveincrease int,
  negativeincrease int,
  total int,
  totaltestresultsincrease int,
  posneg int,
  dataqualitygrade string,
  deathincrease int,
  hospitalizedincrease int,
  hash string,
  commercialscore int,
  negativeregularscore int,
  negativescore int,
  positivescore int,
  score int,
  grade string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  '${code_bucket}/base/states_daily';